"""Create applications table

Revision ID: 71cbcef79cc4
Revises: 682990f22592
Create Date: 2024-08-19 12:06:09.834325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cbcef79cc4'
down_revision = '682990f22592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_application', schema=None) as batch_op:
        batch_op.drop_column('application_type')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=9), nullable=False))
        batch_op.add_column(sa.Column('application_type', sa.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
