"""Create applications table

Revision ID: f9838b2d9e51
Revises: 71cbcef79cc4
Create Date: 2024-08-19 12:07:24.831371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9838b2d9e51'
down_revision = '71cbcef79cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=9), nullable=False))

    # ### end Alembic commands ###
